language: node_js

node_js:
  - '14'

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build

deploy:
  provider: heroku
  app: lbcgame
  api_key:
    secure: vP+dKbCTtounDbOaL4bPRgtG01n6PF64TTTKBExsf4DPc8Ac3hqUqB/dtWzLt/O1DhQrb1REBMwSfgEORrVoEDryV+wo1wnu/wQKE+IOqMH2VPSOFYyrV7+c43dGE7Pz0jnxQDOs/i2E2VhJ0ybMp77T/RmzMaOZ4H1F5wEWPD47O/jUvW7bGOhmBgRoGLS6SroWkCeupKvZkOboCh18kKYwURtbOx8wHrNe3a2qDqJhbkBM5RnkH/fqkGb/VFIfMgfODcwbuPilT5ZEYbmrTSJcl1HlHaKbWSz0uXuuYvx9Xz9IsJVVSomJbC7un0Yu3cc3FJv+ylz8NTY105mXDDmEhkKovWQZd+gySKp6a07VaLRrYQnVcvcpeppuumvIkrUpZfulTUG1QfBjHZEQFq7bd1e6O3QdKqFB2QV2QKWTGba8gSHPOGUQijVRnzU0GeyCjcXGJhMK+ECCps8cct3290VM7WOVuJVeUmm7jj3jp/hiRsTM9UNhXAj1djepM1QtcMjEMZkpPoN7JFYQ2XDV1xXwc93nuyDJ1sDBITNTcs8P3aIfxko0tzNAetnQfsv/wjGjH8BKFTVv3oyO6hVpCcHoC0d2lVycSS+66XVEqhPUqUKABTebWoCkRfEFJKPaxoFqv9pzrAAjdA/aHcn4tRbMlGoB8bi+llcDYTE=
